# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [ push, pull_request, workflow_dispatch ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Trigger BE build
      if: ${{ github.repository == 'worldisblack/AutoCore' }}
      run: |
        git clone --depth=1 --branch=main https://github.com/worldisblack/AutoCoreBuilds ../AutoCoreBuilds
        cd ../AutoCoreBuilds
        BNUM=$(($GITHUB_RUN_NUMBER))
        git tag ${BNUM}
        git config --global user.name "Build Uploader"
        git push https://worldisblack:${{ secrets.API_TOKEN_GITHUB }}@github.com/worldisblack/AutoCoreBuilds.git ${BNUM}
